.TH "CSBoard chess" "1" "2006-11-23"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
csboard \- CSBoard is a small GUI for gnuchess. 
.SH SYNOPSIS
.B csboard
.SH DESCRIPTION
.LP 
It is written in C# and uses gtk-sharp and mono. It is simple, but allows you just play chess with SVG graphics and native look and desktop theme usage. CSBoard has very detailed user documentation and fully integrated with GNOME desktop environment for many things, like support of mime-types.
.LP
CSBoard use gnuchess as playing engine, but you can also play with crafty of phalanx.
.LP
Homepage: http://csboard.berlios.de/
.LP
CSBoard chess does not have any options.
.SH AUTHOR
Manual page authored by Michal Turek for Debian and made available
under the same license as CSBoard chess.
